services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-server
    command: start-dev
    ports:
      - 8080:8080
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-database:5432/keycloak
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: root@123
    depends_on:
      postgres-database:
        condition: service_healthy

volumes:
  pgdata:
    driver: local